# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsctx < Formula
  desc "Fast AWS profile and region switcher"
  homepage "https://github.com/yetmike/awsctx"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.1/awsctx_0.0.1_darwin_amd64.tar.gz"
      sha256 "e852c5d5aa359d278b663684efe3b79268030fb778511aa93e9ff0e9213c2f32"

      def install
        bin.install "awsctx"
        bash_completion.install "bash_autocomplete" => "awsctx"
        zsh_completion.install "zsh_autocomplete" => "_awsctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.1/awsctx_0.0.1_darwin_arm64.tar.gz"
      sha256 "69c61a3fe061996790494c491a8f594026cc123665e237372b3172d04b8e5c8b"

      def install
        bin.install "awsctx"
        bash_completion.install "bash_autocomplete" => "awsctx"
        zsh_completion.install "zsh_autocomplete" => "_awsctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.1/awsctx_0.0.1_linux_amd64.tar.gz"
      sha256 "63c65cf38aa8469e7d14f238958492584d4da874c975279e0b7e1c6ba3c933b9"
      def install
        bin.install "awsctx"
        bash_completion.install "bash_autocomplete" => "awsctx"
        zsh_completion.install "zsh_autocomplete" => "_awsctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.1/awsctx_0.0.1_linux_arm64.tar.gz"
      sha256 "fee70be9976ecefd4fec357f4140baf190a267f23e85cbe111e89ab488520417"
      def install
        bin.install "awsctx"
        bash_completion.install "bash_autocomplete" => "awsctx"
        zsh_completion.install "zsh_autocomplete" => "_awsctx"
      end
    end
  end
end
