# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsctx < Formula
  desc "Fast AWS profile and region switcher"
  homepage "https://github.com/yetmike/awsctx"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.8/awsctx_0.0.8_darwin_amd64.tar.gz"
      sha256 "f4f2363258cc513d8593c65eb4bbff8e1065fdc29a592f881b90d84cec5295a9"

      def install
        bin.install "awsctx"
        bash_completion.install "bash_autocomplete" => "awsctx"
        zsh_completion.install "zsh_autocomplete" => "_awsctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.8/awsctx_0.0.8_darwin_arm64.tar.gz"
      sha256 "569385953352b1d006f6ea09ac76fff7b7098844e864e5140f384d37cdc51b6d"

      def install
        bin.install "awsctx"
        bash_completion.install "bash_autocomplete" => "awsctx"
        zsh_completion.install "zsh_autocomplete" => "_awsctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.8/awsctx_0.0.8_linux_amd64.tar.gz"
      sha256 "513a9ae5688eb639afcb9e7d6e2e28b3427a4063967043134b51bd06e2650455"
      def install
        bin.install "awsctx"
        bash_completion.install "bash_autocomplete" => "awsctx"
        zsh_completion.install "zsh_autocomplete" => "_awsctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.8/awsctx_0.0.8_linux_arm64.tar.gz"
      sha256 "33b617ed59b7976194e1587815cffdef4b8f6072a23b8d42134355d5bb324a06"
      def install
        bin.install "awsctx"
        bash_completion.install "bash_autocomplete" => "awsctx"
        zsh_completion.install "zsh_autocomplete" => "_awsctx"
      end
    end
  end
end
