# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsctx < Formula
  desc "Fast AWS profile and region switcher"
  homepage "https://github.com/yetmike/awsctx"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.6/awsctx_0.0.6_darwin_amd64.tar.gz"
      sha256 "8f15695d1aadec56be9cc19f6b4be0582e285f0deae6e4c8ee4611af80f52f3f"

      def install
        bin.install "awsctx"
        bash_completion.install "awsctx.sh" => "awsctx"
        zsh_completion.install "awsctx.sh" => "_awsctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.6/awsctx_0.0.6_darwin_arm64.tar.gz"
      sha256 "6f00077d5ea6943e6268ec957743b1e18f0fe610b1bb0b034b2a317f3753d906"

      def install
        bin.install "awsctx"
        bash_completion.install "awsctx.sh" => "awsctx"
        zsh_completion.install "awsctx.sh" => "_awsctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.6/awsctx_0.0.6_linux_amd64.tar.gz"
      sha256 "b34140408d6d77337b361cd5de6b5139c8f3d4fd6a7969641e878aac0ef3c09d"
      def install
        bin.install "awsctx"
        bash_completion.install "awsctx.sh" => "awsctx"
        zsh_completion.install "awsctx.sh" => "_awsctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/awsctx/releases/download/v0.0.6/awsctx_0.0.6_linux_arm64.tar.gz"
      sha256 "a67e4bdb850e2ec84d48f945c4dc7c0bf4b5baae7a95941861c784d980718ef5"
      def install
        bin.install "awsctx"
        bash_completion.install "awsctx.sh" => "awsctx"
        zsh_completion.install "awsctx.sh" => "_awsctx"
      end
    end
  end
end
