# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ytcap < Formula
  desc "Distraction-free YouTube TUI with AI summaries and Q&A"
  homepage "https://github.com/yetmike/ytcap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yetmike/ytcap/releases/download/v0.1.0/ytcap_0.1.0_darwin_amd64.tar.gz"
      sha256 "8777dbb462c0f65b24dfedcbc1bfd03a8e74da0225c88a729b3879ba7241dfdf"

      define_method(:install) do
        bin.install "ytcap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yetmike/ytcap/releases/download/v0.1.0/ytcap_0.1.0_darwin_arm64.tar.gz"
      sha256 "a7b9060f3f8ac218aaca19c25f8cd10c0e4203e2b640d195a78729c00467e4e9"

      define_method(:install) do
        bin.install "ytcap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/ytcap/releases/download/v0.1.0/ytcap_0.1.0_linux_amd64.tar.gz"
      sha256 "dfd1e9838466e88cbd5c5f389f2ffcbd8bf2dbe7e9413c13a843101150f96e12"
      define_method(:install) do
        bin.install "ytcap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/ytcap/releases/download/v0.1.0/ytcap_0.1.0_linux_arm64.tar.gz"
      sha256 "9508235d7f361bd2b50b013930b2a9eb7fa136121705c914c8bfa7fbc5875de8"
      define_method(:install) do
        bin.install "ytcap"
      end
    end
  end
end
