# This file was generated by GoReleaser. DO NOT EDIT.
cask "ytcap" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1c470eee63fee5e746e57b6ec9565f45c2023c6b40edffdc1a56e7a45b32006a"
      url "https://github.com/yetmike/ytcap/releases/download/v#{version}/ytcap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "93b7b80cc9999ae0589fe2e1030832299be3bfbc7c7457bed891949c2dbae098"
      url "https://github.com/yetmike/ytcap/releases/download/v#{version}/ytcap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "480c6908ca6283ad37125acac1b6c8ccbe0b64e53f68e6b4cd835d70c63dc6d6"
      url "https://github.com/yetmike/ytcap/releases/download/v#{version}/ytcap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "268e4fd7a7f05279744a9474cf2abadac3f0c365709374b5b0374df04b43721f"
      url "https://github.com/yetmike/ytcap/releases/download/v#{version}/ytcap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ytcap"
  desc "Distraction-free YouTube TUI with AI summaries and Q&A"
  homepage "https://github.com/yetmike/ytcap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ytcap"

  # No zap stanza required

end
