# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ytcap < Formula
  desc "Distraction-free YouTube TUI with AI summaries and Q&A"
  homepage "https://github.com/yetmike/ytcap"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yetmike/ytcap/releases/download/v0.1.0/ytcap_0.1.0_darwin_amd64.tar.gz"
      sha256 "b4a8b5255bab4aff9a95bccc4479f29032010c0d15341f600a0069d1f89078ad"

      define_method(:install) do
        bin.install "ytcap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yetmike/ytcap/releases/download/v0.1.0/ytcap_0.1.0_darwin_arm64.tar.gz"
      sha256 "fed004f7e9dd4ec88bef009b27dfcd55ef1fd0cee6136663f4ef34c7ea16bd08"

      define_method(:install) do
        bin.install "ytcap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/ytcap/releases/download/v0.1.0/ytcap_0.1.0_linux_amd64.tar.gz"
      sha256 "853fbfd3c3893d3a26aeb923609f41c269114aef186f111c691c86fc89c0a471"
      define_method(:install) do
        bin.install "ytcap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yetmike/ytcap/releases/download/v0.1.0/ytcap_0.1.0_linux_arm64.tar.gz"
      sha256 "1eb28e3576c1f1994f614e294387f95be2caf0665eecee120d3422f942142a25"
      define_method(:install) do
        bin.install "ytcap"
      end
    end
  end
end
